import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fun Fact App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.container}>
          Welcome to the Fun Fact Generator
        </h1>

        <div className={styles.grid}>
            
            <p className={styles.title}>
                Did you know that Next.JS is build on top of React?
            </p>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Potato</p>
      </footer>
    </div>
  )
}
